version: '3'

networks:
  laravel:

volumes:
  mysqldata:
    driver: local

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - '${APP_PORT}:80'
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - '9000:9000'
    networks:
      - laravel
  logger:
    image: gliderlabs/logspout:latest
    container_name: logger
    ports:
      - '5000:5000'
    networks:
      - laravel
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - 'syslog+tls://${PT_URL}:${PT_PORT}?filter.name=*nginx*'
    environment:
      SYSLOG_FORMAT: rfc5424
